litellm_settings:
  drop_params: true
model_list:
- litellm_params:
    additional_drop_params:
    - output_config
    - stop_sequences
    api_base: os.environ/NVIDIA_NIM_API_BASE
    api_key: os.environ/NVIDIA_NIM_API_KEY
    model: nvidia_nim/stepfun-ai/step-3.7-flash
  model_name: claude-step-37-flash
- litellm_params:
    additional_drop_params:
    - output_config
    - stop_sequences
    api_base: os.environ/NVIDIA_NIM_API_BASE
    api_key: os.environ/NVIDIA_NIM_API_KEY
    model: nvidia_nim/deepseek-ai/deepseek-v4-flash
  model_name: claude-deepseek-v4-flash
- litellm_params:
    additional_drop_params:
    - output_config
    - stop_sequences
    api_base: os.environ/NVIDIA_NIM_API_BASE
    api_key: os.environ/NVIDIA_NIM_API_KEY
    model: nvidia_nim/deepseek-ai/deepseek-v4-pro
  model_name: claude
- litellm_params:
    additional_drop_params:
    - output_config
    - stop_sequences
    api_base: os.environ/NVIDIA_NIM_API_BASE
    api_key: os.environ/NVIDIA_NIM_API_KEY
    model: nvidia_nim/z-ai/glm-5.2
  model_name: claude-glm-5.2
- litellm_params:
    additional_drop_params:
    - output_config
    - stop_sequences
    api_base: os.environ/MIMO_API_BASE
    api_key: os.environ/MIMO_API_KEY
    model: openai/mimo-v2.5-pro
  model_name: claude-mimo-v2.5-pro
router_settings:
  routing_strategy: latency-based-routing
