services:
  open-webui:
    image: open-webui
    container_name: open-webui

    ports:
      - "3000:8080"

    volumes:
      - /Volumes/Nexus/Documents/Docker/OpenWebui/data:/app/backend/data

    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434

    restart: always

    labels:
      - homepage.group=AI / LLM
      - homepage.name=Open WebUI
      - homepage.icon=open-webui.svg
      - homepage.href=http://open-webui.openwebui.orb.local/
      - homepage.description=本地 LLM 聊天前端

