services:
  litellm: 
    image: litellm
    container_name: litellm
    platform: linux/arm64
    
    ports:
      - "4000:4000"

    env_file:
      - .env

    volumes:
      - ./config.yaml:/app/config.yaml

    command: 
      --config /app/config.yaml
      --port 4000

    restart: always

