model_list:
  - model_name: claude
    litellm_params:
      model: nvidia_nim/stepfun-ai/step-3.7-flash
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: os.environ/NVIDIA_NIM_API_BASE
      additional_drop_params: ["output_config", "stop_sequences"]
  - model_name: claude
    litellm_params:
      model: nvidia_nim/deepseek-ai/deepseek-v4-flash
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: os.environ/NVIDIA_NIM_API_BASE
      additional_drop_params: ["output_config", "stop_sequences"]
  - model_name: claude
    litellm_params:
      model: nvidia_nim/deepseek-ai/deepseek-v4-pro
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: os.environ/NVIDIA_NIM_API_BASE
      additional_drop_params: ["output_config", "stop_sequences"]
  - model_name: claude
    litellm_params:
      model: nvidia_nim/z-ai/glm-5.2
      api_key: os.environ/NVIDIA_NIM_API_KEY
      api_base: os.environ/NVIDIA_NIM_API_BASE
      additional_drop_params: ["output_config", "stop_sequences"]

litellm_settings:
  drop_params: true

router_settings:
  routing_strategy: latency-based-routing
