model_list:
  # - model_name: claude
  #   litellm_params:
  #     # model: nvidia_nim/google/gemma-4-31b-it
  #     model: nvidia_nim/nvidia/nemotron-3-super-120b-a12b
  #     api_key: os.environ/NVIDIA_NIM_API_KEY
  #     api_base: os.environ/NVIDIA_NIM_API_BASE
  - model_name: claude
    litellm_params:
      # model: nvidia_nim/google/gemma-4-31b-it
      model: openrouter/owl-alpha
      api_key: os.environ/OPEN_API_KEY
      api_base: os.environ/OPEN_API_BASE

litellm_settings:
  drop_params: true
