services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr

    environment:
      - PUID=502
      - PGID=20
      - TZ=Asia/Shanghai

    volumes:
      - /Volumes/Nexus/Documents/Docker/music/Lidarr/config:/config
      - /Volumes/Nexus/Documents/Brew/Navidrome/music:/music
      - /Volumes/Nexus/Documents/Docker/music/Lidarr/downloads:/downloads

    ports:
      - "8686:8686"

    restart: always

    labels:
      - homepage.group=媒体 / 影音
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.href=http://lidarr.music.orb.local/
      - homepage.description=音乐库自动化


  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr

    environment:
      - PUID=502
      - PGID=20
      - TZ=Asia/Shanghai

    volumes:
      - /Volumes/Nexus/Documents/Docker/music/Prowlarr/config:/config

    ports:
      - 9696:9696

    restart: always

    labels:
      - homepage.group=媒体 / 影音
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=http://prowlarr.music.orb.local/
      - homepage.description=索引器聚合


  musictag:
    image: xhongc/music_tag_web:latest
    container_name: musictag
 
    environment:
      - PUID=502
      - PGID=20
      - TZ=Asia/Shanghai

    volumes:
      - /Volumes/Nexus/Documents/Docker/music/musictag/data:/app/data
      - /Volumes/Nexus/Documents/Brew/Navidrome/music:/app/media

    ports:
      - 8002:8002

    restart: always

    labels:
      - homepage.group=媒体 / 影音
      - homepage.name=Music Tag
      - homepage.icon=si-musicbrainz
      - homepage.href=http://musictag.music.orb.local/
      - homepage.description=音乐标签编辑

  picard:
    image: jlesage/musicbrainz-picard:latest
    container_name: picard
    
    environment:
      - PUID=502
      - PGID=20
      - TZ=Asia/Shanghai
    
    volumes:
      - /Volumes/Nexus/Documents/Docker/music/Picard/config:/config
      - /Volumes/Nexus/Documents/Brew/Navidrome/music:/storage

    ports:
      - 5800:5800

    restart: always

    labels:
      - homepage.group=媒体 / 影音
      - homepage.name=Picard
      - homepage.icon=si-musicbrainz
      - homepage.href=http://picard.music.orb.local/
      - homepage.description=MusicBrainz Picard
