services:
  moviepilot:
    image: jxxghp/moviepilot-v2:latest
    container_name: moviepilot
    stdin_open: true
    tty: true

    environment:
      - PUID= 502
      - PGID= 20
      - TZ=Asia/Shanghai
      - SUPERUSER= admin
      - SUPERUSER_PASSWORD= moviepilot.1231
      - MOVIEPILOT_AUTO_UPDATE=false 
      - GITHUB_PROXY=https://ghproxy.com/
 
    volumes:
      - /Volumes/Nexus/Documents/Docker/movie/moviepilot/config:/config
      - /Volumes/Nexus/Documents/Docker/movie/movies:/media
      - /Volumes/Nexus/Documents/Docker/movie/moviepilot/core:/moviepilot/.cache/ms-playwright

    ports:
      - 3300:3000
      - 3301:3001

    extra_hosts:
      - host.docker.internal:host-gateway

    restart: always

