services:
  moviepilot:
    image: jxxghp/moviepilot-v2:latest
    container_name: moviepilot
    stdin_open: true
    tty: true

    environment:
      - PUID= 502
      - PGID= 20
      - TZ=Asia/Shanghai
      - SUPERUSER= admin
      - MOVIEPILOT_AUTO_UPDATE=false 
 
    volumes:
      - /Volumes/Nexus/Documents/Docker/movie/moviepilot/config:/config
      - /Volumes/Nexus/Documents/Docker/movie/movies:/media
      - /Volumes/Nexus/Documents/Docker/movie/moviepilot/core:/moviepilot/.cache/ms-playwright

    ports:
      - 3300:3000
      - 3301:3001

    extra_hosts:
      - host.docker.internal:host-gateway

    restart: always

    labels:
      - homepage.group=媒体 / 影音
      - homepage.name=MoviePilot
      - homepage.icon=jellyfin.png
      - homepage.href=http://moviepilot.movies.orb.local/
      - homepage.description=影视自动化

